---
name: JSAN-ServerSide
version: 0.04
author:
  - 'Dave Rolsky, <autarch@urth.org>'
abstract: Manage JSAN dependencies server side instead of with XMLHttpRequest
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  JSAN::Parse::FileDeps: 0
  Params::Validate: 0
  Test::More: 0
  URI::ToDisk: 0
build_requires:
  Module::Build: 0
provides:
  JSAN::ServerSide:
    file: lib/JSAN/ServerSide.pm
    version: 0.04
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
